index.ts

Fix yearn folder path

---

gnosis/Gov Weekly/Update Week-3 2021, 02-16-21.md

Added file containing Gov Updates for Week 3 2021.
Includes 3GIPs + 2 Grant Announcements

Create Update for Week-3 2021

---

aave/Gov Weekly/Gov WeeklyUpdate Week 7 02-23-21.

Week 7 gov summary. 
2 major recent votes cover and 4 proposals.
Let me know
Cheers

Create Gov WeeklyUpdate Week 7 02-23-21.

---

synthetix/Gov Weekly/Update Week 8 2021, 02-24-2021.md

Slightly different Governance format from other protocols, wondering what format to use for Synthetix' weekly update

Synthetix update w8 - Angel de benji 

---

scripts/add_new_protocol.sh

just do like: `./scripts/add_new_protocol.sh ${protocolName}`

feat: simple script to init a skeleton director for new protocol

---

README.md

update logo and reposition social links

---

compound/Gov Weekly/Week 9 2021 03-03-21.md

Adding my gov update for week 9

Create Week 9 2021 03-03-21.md

---

pooltogether/Gov Weekly/Update Week 9 2021 03-03-21.md

included discussion posts from last week that still had significant activity this week

Angel de benji gov weekly w9 pool together

---

rarible/Gov Weekly/Week 9 2021 03-05-21.md

Wondering if I should also include improvement proposals and feedback from Rarible's Feedback page (https://feedback.rarible.com). It does not have the conventional DAO voting processes but it does seem to be a source of changes to Rarible platform.

Create Week 9 2021 03-05-21.md

---

pooltogether/Gov Weekly/Update Week 12 2021 26-03-21.md

Noticed that I could not find PoolTogether in the boardroom browser app. Not sure if this was on my end.
Used links to snapshot and PoolTogether's website for live and recent votes.

Create PoolTogether Update Week 12 2021 26-03-21.md

---

protocols/compound/index.json
protocols/fei/index.json
protocols/gitcoin/index.json
protocols/idlefinance/index.json
protocols/indexed/index.json
protocols/inverse/index.json
protocols/pooltogether/index.json
protocols/radicle/index.json
protocols/uniswap/index.json
scripts/add_new_protocol.sh
types.ts

* Key `"disableTreasuryNav": false` is defaulted to false
so that any onboarded protocol will have it enabled by default
* Add `"disableTreasuryNav": true` for compoundish projects

Add a flag to disable treasury nav

---

protocols/council.graphprotocol.eth/index.json
protocols/dai-prize-pool/index.json
protocols/graphprotocol.eth/index.json
protocols/pasta/index.json
protocols/pickle/index.json
protocols/pooltogether/index.json
protocols/vsp.eth/index.json
protocols/ybaby.eth/index.json

This PR updates a few of the protocol names to match what's shown on [Snapshot](http://snapshot.org/).

chore: update protocol names

---

protocols/instadapp/contracts/governance.json
protocols/instadapp/contracts/token.json
protocols/instadapp/index.json
protocols/instadapp/overview.md

This PR updates a few fields in the Instadapp protocol info.

fix: update instadapp

---

protocols/drc/index.json

update treasuryAddresses for DRC

---

protocols/shapeshift/events.json

Add upcoming events

---

protocols/aragon/overview.md

Add the Overview for the Aragon Project

Add Aragon overview

---

protocols/banklessvault.eth/events.json

My first update. Testing things out.

Bankless event update

---

protocols/algorand/index.json
protocols/algorand/overview.md

**What this PR does**
- Added Overview for Algorand

Added overview for Algorand

---

protocols/prime-dao/events.json
protocols/prime-dao/index.json
protocols/prime-dao/overview.md

adds config for PrimeDAO

---

protocols/gitcoin/gitcoin-weekly1.md

Gitcoin weekly update 1

---

protocols/gitcoin/resources/Gov Weekly/Gitcoin - 10-1-21.md

Create Gitcoin - 10-1-21.md

---

protocols/perpetualprotocol/events.json
protocols/perpetualprotocol/index.json
protocols/perpetualprotocol/overview.md
protocols/perpetualprotocol/resources/Community Calls/CommunityCall1.md
protocols/perpetualprotocol/resources/Community Calls/CommunityCall2.md
protocols/perpetualprotocol/resources/Community Calls/CommunityCall3.md
protocols/perpetualprotocol/resources/Community Calls/CommunityCall4.md
protocols/perpetualprotocol/resources/Community Calls/CommunityCall5.md
protocols/perpetualprotocol/resources/Community Calls/CommunityCall6.md
protocols/perpetualprotocol/resources/Community Calls/CommunityCall7.md
protocols/perpetualprotocol/resources/Grants Program/FundedGrants.md
protocols/perpetualprotocol/resources/Grants Program/RFPs.md
protocols/perpetualprotocol/resources/Grants Program/committee.md
protocols/perpetualprotocol/resources/Grants Program/overview.md

PR to add [Perpetual Protocol ](https://perp.fi) as a project to Boardroom.

Add Perpetual Protocol to Boardroom with Resources

---

protocols/radicle/resources/Weekly Updates/Weekly Update 2021-10-15.md

no updates to events.json this week

New Weekly Update for Radicle from witwiki

---

protocols/piedao/resources/Update PieDAO 05-11-21.md

New Weekly Update for PieDAO from kitblake

Update PieDAO 05-11-21.md

---

protocols/bprotocol/index.json

bprotocol treasury page is broken, this fix it

Disable bprotocol treasury page

---

protocols/thelao/overrview.md

add thelao overview

---

protocols/bancor/index.json

Reverts boardroom-inc/protocol-Info#494

Revert "Disable bancor"

---

protocols/keep2r.eth/index.json
protocols/keep2r.eth/overview.md

Cannot seem to find their forum.

Fix keep2r

---

protocols/0x/index.json
protocols/compound/overview.md
protocols/compoundgrants/overview.md
protocols/defidollar/overview.md
protocols/gov.dhedge.eth/overview.md
protocols/indexed/overview.md
protocols/keep2r.eth/overview.md
protocols/pooltogether/overview.md
protocols/synthetix/overview.md

**_Minor formatting fixes have been done in this PR._** 
**Integrations PRs Merged**
Threshold network : https://github.com/boardroom-inc/protocol-Info/pull/516
BitDAO : https://github.com/boardroom-inc/protocol-Info/pull/515
LexPunk: https://github.com/boardroom-inc/protocol-Info/pull/280
Below fixes were contributed by @cryptosabago 
**DefiDollar**
- Added logo
- Fixed overview formatting and added links
**PoolTogether**
- Added logo
- Fixed overview formatting and added links
**CompoundGrants**
- Added logo
- Fixed overview formatting and added links
**Synthetix**
- Added logo
- Fixed overview formatting and added links
**Compound**
- Added logo
- Fixed overview formatting and added social links
**Indexed Finance**
- Added overview and social links
- Added logo
- Fixed index.json file …

Patch Audit Fixes 2

---

protocols/opendao/index.json

Added opendao treasury

---

protocols/radicle/overview.md

Fixed formatting.
Removed footer.

Fix radicle overview

---

protocols/tokenlon.eth/index.json

Fix: TokenLon - add forum link

---

protocols/gooddollar/index.json

Disabled as it fails after first proposal because we dont support weighted voting

Disable Gooddollar

---

protocols/blockzerolabs.eth/index.json

They have active governance now

re-enable: Blockzero Labs

---

protocols/yamv2/index.json
protocols/yamv2/overview.md

They were never enabled before so enabling them now

re-enable Yam Finance

---

protocols/gasdao/index.json

GasDAO: add treasury address

---

protocols/braintrust/index.json

Braintrust: add treasury address

---

protocols/yamv2/index.json

Yam Finance: fix cname mismatch

---

protocols/basisdollar.eth/index.json

Disable: Inactive and unreachable

disable: Basis Dollar

---

protocols/angle/index.json

Enabling to support on-chain governance
- https://github.com/boardroom-inc/governance-sdk/pull/268

enable: angle

---

protocols/dsd.eth/index.json

**Reason for disabling:** Unreachable and Inactive for a year

Disable: dynamic set dollar

---

protocols/Juicebox/overview.md

Juicebox: add more info in overview

---

protocols/bleepsdao/index.json
protocols/bleepsdao/overview.md

Update overview page and add treasury address. 
This Integration was previously paused as we couldn't find DAO Contract addresses, resuming now after getting details from their core team.

Add/Update: bleepsdao

---

protocols/cream-finance.eth/index.json
protocols/cream-finance.eth/overview.md

It was never enabled and was added by the script, allowing it now.

enable: cream finance

---

protocols/creativeorg/index.json
protocols/creativeorg/overview.md

Removing their forum temporarily and enabling their snapshot governance
Note:
Their treasury address is verified, they have $0 as of now.

enable: creativeorg

---

protocols/candle/index.json

Testing Candle's readonly snapshot goverance

disable2test: candle

---

protocols/defrag/overview.md

fix: defrag governance structure image

---

protocols/apwineeth/index.json

I am seeing both proposals and votes in the db, so this should be good to go now.

Enable apwine

---

protocols/m0/overview.md

Add overview for M^0 protocol https://boardroom.io/m0/proposals

Add M^0 protocol overview
